### ISSUE TITLE
[BE] Spring Rest Docs 적용

### ISSUE THREAD

**Issue by sigridjineth** [codesquad-member-2020/todo-5#2]
## 작업할 사항
• API 문서 자동화를 위하여 Swagger 대신 Spring Docs API를 적용해본다.
• Spring Docs API 적용 이유는 API 테스트를 통과할 때만 문서가 자동으로 작성되기 때문이다.

https://woowabros.github.io/experience/2018/12/28/spring-rest-docs.html

**Comment by realsigridjin** [comment]
너무 yak shaving인 것 같아 나중에 학습하고 적용하는 것으로 한다.
