### ISSUE TITLE
[BE] 2주차 해결해야 할 사항

### ISSUE THREAD

**Issue by MuseopKim** [codesquad-member-2020/todo-5#72]
## 개선해야 될 점
1. 전체 카테고리를 출력하는 부분과 특정 카테고리를 불러오는 부분의 로직이 불일치 합니다.
2. CRUD 요청이 성공 했을 경우, 해당 객체를 json으로 반환하는 것이 아닌 id, status, date로 출력 하도록 통일 해야 합니다.
```
[예시]
{		
    "id": 1,			
    "status": true,	
    "data": null		
}
```

3. delete와 isdeleted 값이 공존 합니다. (하나는 삭제 필요)
4. int의 기본형이 0인데, 0은 null과 같은 뜻.
5. 모든 category를 출력할 때 각 category가 보유하고 있는 task 중, deleted 값이 false인 값들만 리턴을 하려 했습니다. 그러나 해당 기능의 복잡성 때문에 현재는 미구현 상태로 deleted 키를 함께 반환 합니다.
6. 카테고리 삭제 요청시 응답으로 삭제 된 카테고리의 전체 정보를 반환 합니다. id, status, data 형식으로 일치 시켜야 합니다.
7. Task 삭제 요청 시 REQUEST BODY가 존재하지 않음에도 불구하고 요청이 실행 됩니다. 카테고리 삭제 요청과 같이 요청 형식을 다음과 같은 형식으로 통일하는 수정이 요구 됩니다.
```
[예시]
{
	"isDeleted": true
}
```
8. Task 이동시 이동 된 category에서의 priority 싱크가 맞지 않습니다.
9. 특정 Task를 show 할때 isDeleted가 미출력 됩니다. (추가 해야함)
10. 특정 카테고리로 Task를 이동시 해당 카테고리가 존재하지 않을 경우에도 요청이 실행 됩니다. 예외처리가 필요 합니다.

**Comment by realsigridjin** [comment]
API 문서의 많은 수정이 요구되는 사항이 있어, 원활한 협업을 목표로 하여 priority 중복 정렬과 Task 이동 시 예외처리 정도만 수정해야 할 것 같습니다.
